---
image: cr.agilicus.com/corp-tools/docker-compose

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

services:
  - name: docker:dind

stages:
  - build

build:
  stage: build
  script: |
    if [ -f distribution/docker/Dockerfile ]
    then
      docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY;
      docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/druid:$CI_COMMIT_REF_NAME -f distribution/docker/Dockerfile .
      docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/druid:$CI_COMMIT_REF_NAME
      if [ "$CI_COMMIT_REF_NAME" = "integration" ];
      then
        echo Tag $CI_REGISTRY/$CI_PROJECT_NAMESPACE/druid:$CI_COMMIT_REF_NAME with $CI_REGISTRY/$CI_PROJECT_NAMESPACE/druid:latest
        docker tag $CI_REGISTRY/$CI_PROJECT_NAMESPACE/druid:$CI_COMMIT_REF_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/druid:latest
        docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/druid:latest
      fi
    fi
